[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    madhephaestus/ESP32Servo
    adafruit/Adafruit PWM Servo Driver Library @ ^2.4.1